# This file provides sane defaults for tank games config.  The values in this file can be overridden
# by the yaml file pointed to by TANK_GAME_UI_CONFIG.

engineInterface:
  timeout: 3 # seconds

backend:
  # Assume this config is being used inside the docker container
  gamesFolder: /data/games/
  port: 3333

defaultGameVersion:
  logEntryFormatters:
    start_of_day: "Start of day {day}"
    move: "{subject} moved to {target}"
    shoot: "{subject} shot at {target} ({hit})"
    buy_action: "{subject} traded {gold} gold for actions"
    donate: "{subject} donated {donation} pre-tax gold to {target}"
    upgrade_range: "{subject} upgraded their range"
    bounty: "{subject} placed a {bounty} gold bounty on {target}"
    stimulus: "{subject} granted a stimulus of 1 action to {target}"
    grant_life: "{subject} granted 1 life to {target}"

  entityDescriptors:
    tank:
      featuredAttribute: attr:health:value
      indicatorBackground: "#000"
      indicatorDefaultColor: "#fff"
      tileColor:
        - background: "url('/assets/Tank.png')"
          textColor: "#fff"

    "dead-tank":
      featuredAttribute: attr:health:value
      tileColor:
        - background: "url('/assets/DeadTank.png')"
          textColor: "#fff"

  floorTileDescriptors:
    gold_mine:
      color: "var(--tank-game-orange)"

  councilPlayerTypes:
    - councilor
    - senator

gameVersions:
    3:
      manual: /manuals/Tank_Game_Rules_v3.pdf
      entityDescriptors:
        tank:
          badgeAttribute: attr:actions:value
          badgeColor: "#00f"
          badgeTextColor: "#fff"
          indicators:
            - symbol: B
              expr:
                var: attr:bounty:value
                gt: 0
              color: orange

        wall:
          tileColor:
          - background: "url('/assets/Wall-1.png')"
            textColor: "#fff"
            expr:
              eq: 1
              var: attr:health:value
          - background: "url('/assets/Wall-2.png')"
            textColor: "#fff"
            expr:
              eq: 2
              var: attr:health:value
          - background: "url('/assets/Wall-4.png')"

    4:
      manual: /manuals/Tank_Game_Rules_v4.pdf
      entityDescriptors:
        tank:
          badgeAttribute: attr:actions:value
          badgeColor: "#00f"
          badgeTextColor: "#fff"
          indicators:
            - symbol: B
              expr:
                var: attr:bounty:value
                gt: 0
              color: orange

        wall:
          tileColor:
          - background: "url('/assets/Wall-1.png')"
            textColor: "#fff"
            expr:
              eq: 1
              var: attr:health:value
          - background: "url('/assets/Wall-2.png')"
            textColor: "#fff"
            expr:
              eq: 2
              var: attr:health:value
          - background: "url('/assets/Wall-3.png')"
            expr:
              eq: 3
              var: attr:health:value
          - background: "url('/assets/Wall-4.png')"
            expr:
              eq: 4
              var: attr:health:value
          - background: "url('/assets/Wall-5.png')"
            expr:
              eq: 5
              var: attr:health:value
          - background: "url('/assets/Wall-6.png')"
